app = 'agar2-0'
primary_region = 'ord'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[processes]
app = ".meteor/heroku_build/bin/node $NODEJS_PARAMS .meteor/heroku_build/app/main.js"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/nodejs"]
